rm -f *.obj
rm -f *.list
rm -f *.fw
rm -f *.map

# --- Building blm.list
nfas -t -W3 -R -lm 0 -C -chip nfp-4xxx-b0  -DBLM_CUSTOM_CONFIG -DNFP_LIB_ANY_NFAS_VERSION -I. -I/c_packetprocessing/microc/blocks -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -I/components/standardlibrary/microcode/src -DBLM_CUSTOM_CONFIG -DSINGLE_NBI -DPKT_NBI_OFFSET= -DBLM_BLQ_EMEM_TYPE=emem -DNBII=8 -DBLM_INSTANCE_ID=0 -DBLM_INIT_EMU_RINGS -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/blocks/blm/ -I/c_packetprocessing/microc/blocks/blm/_h -I/c_packetprocessing/microc/blocks/blm/_uc -o blm.list /c_packetprocessing/microc/blocks/blm/blm_main.uc

# --- Building pkt_collect.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fepkt_collect.list /dtree/statlog/micro_c/pkt_collect.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /c_packetprocessing/microc/lib/pkt/libpkt.c /c_packetprocessing/microc/lib/net/libnet.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature1.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature1.list /dtree/statlog/micro_c/feature1.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature2.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature2.list /dtree/statlog/micro_c/feature2.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature3.list /dtree/statlog/micro_c/feature3.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature4.list /dtree/statlog/micro_c/feature4.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature5.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature5.list /dtree/statlog/micro_c/feature5.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature6.list /dtree/statlog/micro_c/feature6.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature7.list /dtree/statlog/micro_c/feature7.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature8.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature8.list /dtree/statlog/micro_c/feature8.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature9.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature9.list /dtree/statlog/micro_c/feature9.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature10.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature10.list /dtree/statlog/micro_c/feature10.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature11.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature11.list /dtree/statlog/micro_c/feature11.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature12.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature12.list /dtree/statlog/micro_c/feature12.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature13.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature13.list /dtree/statlog/micro_c/feature13.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature14.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature14.list /dtree/statlog/micro_c/feature14.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature15.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature15.list /dtree/statlog/micro_c/feature15.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature16.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature16.list /dtree/statlog/micro_c/feature16.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature17.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature17.list /dtree/statlog/micro_c/feature17.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature18.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature18.list /dtree/statlog/micro_c/feature18.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature19.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature19.list /dtree/statlog/micro_c/feature19.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature20.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature20.list /dtree/statlog/micro_c/feature20.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature21.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature21.list /dtree/statlog/micro_c/feature21.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature22.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature22.list /dtree/statlog/micro_c/feature22.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature23.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature23.list /dtree/statlog/micro_c/feature23.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature24.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature24.list /dtree/statlog/micro_c/feature24.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature25.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature25.list /dtree/statlog/micro_c/feature25.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature26.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature26.list /dtree/statlog/micro_c/feature26.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature27.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature27.list /dtree/statlog/micro_c/feature27.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature28.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature28.list /dtree/statlog/micro_c/feature28.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature29.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature29.list /dtree/statlog/micro_c/feature29.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature30.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature30.list /dtree/statlog/micro_c/feature30.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature31.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature31.list /dtree/statlog/micro_c/feature31.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature32.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature32.list /dtree/statlog/micro_c/feature32.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature33.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature33.list /dtree/statlog/micro_c/feature33.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature34.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature34.list /dtree/statlog/micro_c/feature34.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature35.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature35.list /dtree/statlog/micro_c/feature35.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build feature36.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Fefeature36.list /dtree/statlog/micro_c/feature36.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_1.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_1.list /dtree/statlog/micro_c/result_collect1_1.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_2.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_2.list /dtree/statlog/micro_c/result_collect1_2.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_3.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_3.list /dtree/statlog/micro_c/result_collect1_3.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_4.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_4.list /dtree/statlog/micro_c/result_collect1_4.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_5.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_5.list /dtree/statlog/micro_c/result_collect1_5.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_6.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_6.list /dtree/statlog/micro_c/result_collect1_6.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_7.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_7.list /dtree/statlog/micro_c/result_collect1_7.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_8.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_8.list /dtree/statlog/micro_c/result_collect1_8.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect1_9.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect1_9.list /dtree/statlog/micro_c/result_collect1_9.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect2_1.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect2_1.list /dtree/statlog/micro_c/result_collect2_1.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect2_2.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect2_2.list /dtree/statlog/micro_c/result_collect2_2.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Build result_collect3_1.list
nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/dtree/statlog/micro_c -I/c_packetprocessing/microc/include -I/c_packetprocessing/microc/lib -I/c_packetprocessing/microc/blocks/blm -I/c_packetprocessing/microc/blocks/blm/_h -I/components/standardlibrary/include -I/components/standardlibrary/microcode/include -Feresult_collect3_1.list /dtree/statlog/micro_c/result_collect3_1.c /c_packetprocessing/microc/lib/nfp/libnfp.c /c_packetprocessing/microc/lib/std/libstd.c /components/standardlibrary/microc/src/rtl.c

# --- Link code
nfld -chip nfp-4xxx-b0 -mip -rtsyms -o statlog.fw -map statlog.map -u i32.me0 -l pkt_collect.list -u i32.me1 -l feature1.list -u i32.me2 -l feature2.list -u i32.me3 -l feature3.list -u i32.me4 -l feature4.list -u i32.me5 -l feature5.list -u i32.me6 -l feature6.list -u i32.me7 -l feature7.list -u i32.me8 -l feature8.list -u i32.me9 -l feature9.list -u i32.me10 -l feature10.list -u i32.me11 -l feature11.list -u i33.me0 -l feature12.list -u i33.me1 -l feature13.list -u i33.me2 -l feature14.list -u i33.me3 -l feature15.list -u i33.me4 -l feature16.list -u i33.me5 -l feature17.list -u i33.me6 -l feature18.list -u i33.me7 -l feature19.list -u i33.me8 -l feature20.list -u i33.me9 -l feature21.list -u i33.me10 -l feature22.list -u i33.me11 -l feature23.list -u i34.me0 -l feature24.list -u i34.me1 -l feature25.list -u i34.me2 -l feature26.list -u i34.me3 -l feature27.list -u i34.me4 -l feature28.list -u i34.me5 -l feature29.list -u i34.me6 -l feature30.list -u i34.me7 -l feature31.list -u i34.me8 -l feature32.list -u i34.me9 -l feature33.list -u i34.me10 -l feature34.list -u i34.me11 -l feature35.list -u i35.me0 -l feature36.list -u i35.me1 -l result_collect1_1.list -u i35.me2 -l result_collect1_2.list -u i35.me3 -l result_collect1_3.list -u i35.me4 -l result_collect1_4.list -u i35.me5 -l result_collect1_5.list -u i35.me6 -l result_collect1_6.list -u i35.me7 -l result_collect1_7.list -u i35.me8 -l result_collect1_8.list -u i35.me9 -l result_collect1_9.list -u i35.me10 -l result_collect2_1.list -u i35.me11 -l result_collect2_2.list -u i36.me0 -l result_collect3_1.list -u ila0.me0 -l blm.list -i i8 -e /components/standardlibrary/picocode/nfp6000/catamaran/catamaran.npfw
