rm -f *.obj
rm -f *.list
rm -f *.fw
rm -f *.map

# --- Building blm.list
/opt/netronome/bin/nfas -t -W3 -R -lm 0 -C -chip nfp-4xxx-b0  -DBLM_CUSTOM_CONFIG -DNFP_LIB_ANY_NFAS_VERSION -I. -I/home/admin2/c_packetprocessing/microc/blocks -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -I/opt/netronome/components/standardlibrary/microcode/src -DBLM_CUSTOM_CONFIG -DSINGLE_NBI -DPKT_NBI_OFFSET= -DBLM_BLQ_EMEM_TYPE=emem -DNBII=8 -DBLM_INSTANCE_ID=0 -DBLM_INIT_EMU_RINGS -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/blocks/blm/ -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/home/admin2/c_packetprocessing/microc/blocks/blm/_uc -o blm.list /home/admin2/c_packetprocessing/microc/blocks/blm/blm_main.uc


### Island 32 ####
# --- Building pkt_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/pkt_collect_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/pkt_collect_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature3_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature3_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature4_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature4_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature6_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature6_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature7_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/feature7_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build result_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_32_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/result_collect_32_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_32_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island32/result_collect_32_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c


### Island 33 ####
# --- Building pkt_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/pkt_collect_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/pkt_collect_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature3_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature3_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature4_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature4_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature6_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature6_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature7_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/feature7_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build result_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_33_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/result_collect_33_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_33_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island33/result_collect_33_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

### Island 34 ####
# --- Building pkt_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/pkt_collect_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/pkt_collect_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature3_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature3_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature4_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature4_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature6_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature6_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature7_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/feature7_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build result_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_34_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/result_collect_34_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_34_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island34/result_collect_34_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c


### Island 35 ####
# --- Building pkt_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/pkt_collect_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/pkt_collect_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature3_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature3_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature4_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature4_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature6_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature6_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature7_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/feature7_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build result_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_35_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/result_collect_35_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_35_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island35/result_collect_35_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c


### Island 36 ####
# --- Building pkt_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/pkt_collect_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fepkt_collect_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/pkt_collect_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /home/admin2/c_packetprocessing/microc/lib/pkt/libpkt.c /home/admin2/c_packetprocessing/microc/lib/net/libnet.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature3.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature3_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature3_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature3_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature4.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature4_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature4_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature4_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature6.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature6_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature6_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature6_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build feature7.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature7_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Fefeature7_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/feature7_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c

# --- Build result_collect.list
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_36_1.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/result_collect_36_1.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c
/opt/netronome/bin/nfcc -W3 -chip nfp-4xxx-b0 -Qspill=7 -Qnn_mode=1 -Qno_decl_volatile -single_dram_signal -Qnctx_mode=8 -FI config.h  -DBLM_CUSTOM_CONFIG -I. -I/home/admin2/ML_NIC/dtree/land_mine/micro_c -I/home/admin2/c_packetprocessing/microc/include -I/home/admin2/c_packetprocessing/microc/lib -I/home/admin2/c_packetprocessing/microc/blocks/blm -I/home/admin2/c_packetprocessing/microc/blocks/blm/_h -I/opt/netronome/components/standardlibrary/include -I/opt/netronome/components/standardlibrary/microcode/include -Feresult_collect_36_2.list /home/admin2/ML_NIC/dtree/ablation/micro_c2/island36/result_collect_36_2.c /home/admin2/c_packetprocessing/microc/lib/nfp/libnfp.c /home/admin2/c_packetprocessing/microc/lib/std/libstd.c /opt/netronome/components/standardlibrary/microc/src/rtl.c


 # --- Link code
/opt/netronome/bin/nfld -chip nfp-4xxx-b0 -mip -rtsyms -o cicids.fw -map cicids.map -u i32.me0 -l pkt_collect_32_1.list -u i32.me1 -l feature3_32_1.list -u i32.me2 -l feature4_32_1.list -u i32.me3 -l feature6_32_1.list -u i32.me4 -l feature7_32_1.list -u i32.me5 -l result_collect_32_1.list -u i32.me6 -l pkt_collect_32_2.list -u i32.me7 -l feature3_32_2.list -u i32.me8 -l feature4_32_2.list -u i32.me9 -l feature6_32_2.list -u i32.me10 -l feature7_32_2.list -u i32.me11 -l result_collect_32_2.list -u i33.me0 -l pkt_collect_33_1.list -u i33.me1 -l feature3_33_1.list -u i33.me2 -l feature4_33_1.list -u i33.me3 -l feature6_33_1.list -u i33.me4 -l feature7_33_1.list -u i33.me5 -l result_collect_33_1.list -u i33.me6 -l pkt_collect_33_2.list -u i33.me7 -l feature3_33_2.list -u i33.me8 -l feature4_33_2.list -u i33.me9 -l feature6_33_2.list -u i33.me10 -l feature7_33_2.list -u i33.me11 -l result_collect_33_2.list -u i34.me0 -l pkt_collect_34_1.list -u i34.me1 -l feature3_34_1.list -u i34.me2 -l feature4_34_1.list -u i34.me3 -l feature6_34_1.list -u i34.me4 -l feature7_34_1.list -u i34.me5 -l result_collect_34_1.list -u i34.me6 -l pkt_collect_34_2.list -u i34.me7 -l feature3_34_2.list -u i34.me8 -l feature4_34_2.list -u i34.me9 -l feature6_34_2.list -u i34.me10 -l feature7_34_2.list -u i34.me11 -l result_collect_34_2.list -u i35.me0 -l pkt_collect_35_1.list -u i35.me1 -l feature3_35_1.list -u i35.me2 -l feature4_35_1.list -u i35.me3 -l feature6_35_1.list -u i35.me4 -l feature7_35_1.list -u i35.me5 -l result_collect_35_1.list -u i35.me6 -l pkt_collect_35_2.list -u i35.me7 -l feature3_35_2.list -u i35.me8 -l feature4_35_2.list -u i35.me9 -l feature6_35_2.list -u i35.me10 -l feature7_35_2.list -u i35.me11 -l result_collect_35_2.list -u i36.me0 -l pkt_collect_36_1.list -u i36.me1 -l feature3_36_1.list -u i36.me2 -l feature4_36_1.list -u i36.me3 -l feature6_36_1.list -u i36.me4 -l feature7_36_1.list -u i36.me5 -l result_collect_36_1.list -u i36.me6 -l pkt_collect_36_2.list -u i36.me7 -l feature3_36_2.list -u i36.me8 -l feature4_36_2.list -u i36.me9 -l feature6_36_2.list -u i36.me10 -l feature7_36_2.list -u i36.me11 -l result_collect_36_2.list -u ila0.me0 -l blm.list -i i8 -e /opt/netronome/components/standardlibrary/picocode/nfp6000/catamaran/catamaran.npfw
